Zawodnicy/ZawodnicyWebApp/Controllers/PanelAdministracyjnyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ZawodnicyWebApp.Models;
using ZawodnicyWebApp.Operations;

namespace ZawodnicyWebApp.Controllers
{
    
    [Authorize(Roles = "zarzadca")]
    public class PanelAdministracyjnyController : Controller
    {
        // wykorzystanie wstrzyknietych do startup zaleznosci Identity
        private readonly UserManager<IdentityUser> _userManager;
        private AccountUsersOperation _AccountUserOperation;
        public PanelAdministracyjnyController(UserManager<IdentityUser> userManager, AccountUsersOperation accountUsersOperation)
        {
            _userManager = userManager;
            _AccountUserOperation = accountUsersOperation;
        }
 
        
        /// <summary>
        /// Obsluga userow przeniesiona do klasy AccounUsersOperation ktora zostala wstrzyknieta w startup i tu wykorzystana
        /// </summary>
        /// <returns></returns>
        //public async Task<List<UserIdent>> GetAllUsers()
        //{
        //    var Userzy = _userManager.Users.ToList();                 //lista userów Identity

        //    List<UserIdent> userzyList = new List<UserIdent>();  //lista userow moja

        //    foreach (var item in Userzy)
        //    {
        //        var roles = await _userManager.GetRolesAsync(item); //lista ról dla usera item

        //        string allroles = "";

        //        foreach (var r in roles)    //dodanie listy ról do wynikowego napisu
        //        {
        //            if (allroles=="")
        //            {
        //                allroles = String.Format("{0}{1}{2}", allroles, " ", r);
        //            }
        //            else
        //            {
        //                allroles = String.Format("{0}{1}{2}", allroles, " / ", r);
        //            }
                    
        //        }

        //        userzyList.Add(new UserIdent()
        //        {
        //            Name = item.UserName, //u.UserName,

        //            Role = allroles
        //        });
        //    }

        //    return userzyList;
        //} 

        // GET: PanelAdministracyjnyController
        public async Task<ActionResult> Index()
        {
            List<UserIdent> lista = new List<UserIdent>();

            //lista = await GetAllUsers();
            lista = await _AccountUserOperation.GetAllUsers();

            return View(lista);
        }

        // GET: PanelAdministracyjnyController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PanelAdministracyjnyController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PanelAdministracyjnyController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PanelAdministracyjnyController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PanelAdministracyjnyController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PanelAdministracyjnyController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PanelAdministracyjnyController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Zawodnicy/ZawodnicyWebApp/Controllers/TajneController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ZawodnicyWebApp.Controllers
{
    [Authorize(Roles = "wazny,zarzadca")]
    public class TajneController : Controller
    {
        // GET: TajneController
        public ActionResult Index()
        {
            return View();
        }

        // GET: TajneController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TajneController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TajneController/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TajneController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: TajneController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TajneController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: TajneController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Zawodnicy/ZawodnicyWebApp/Controllers/TrenerzyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using ZawodnicyWebApp.Models;

namespace ZawodnicyWebApp.Controllers
{
    public class TrenerzyController : Controller
    {
        //Pobranie wstrzyknietych w stratup zaleznosci
        public IConfiguration Configuration;
        private JWToken _JWToken;
        public TrenerzyController(IConfiguration confiruration, JWToken jwToken)
        {
            Configuration = confiruration;
            _JWToken = jwToken;
        }

        //Pobranie do klasy danych z appsettings.json
        public ContentResult OnGet()
        {
            //przy zmianie URL wystarczy wskazac inny klucz w appsettings niz RestApiUrl:HostUrl
            //lub w appsettings.js podmieniać HostUrl
            var myRestUrl = Configuration["RestApiUrl:HostUrl"];

            return Content($"{myRestUrl}");
        }
        // --- Koniec pobrania danych z appsettings ---
 
        //zmienna do przechowywania URL do REST pobranego metodą OnGet()
        private string _restpath;
        //nazwa wywoływanego contorllera
        private string _controllername = "trenerzyApi";

        // GET: TrenerzyController
        public async Task<ActionResult> Index()
        {
            _restpath = $"{OnGet().Content}{_controllername}";
            List<Trener> trenerzyList = new List<Trener>();
                       
            using (var httpClient = new HttpClient())
            {
                //Dodanie przed using naglowka autoryzacji z tokenem
                httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _JWToken.TokenString);
                using (var response = await httpClient.GetAsync($"{_restpath}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    trenerzyList = JsonConvert.DeserializeObject<List<Trener>>(apiResponse);
                }
            }

                return View(trenerzyList);
        }

        // GET: TrenerzyController/Details/{id}
        public async Task<ActionResult> Details(int id)
        {
            _restpath = $"{OnGet().Content}{_controllername}";

            Trener t = new Trener();
            using (var httpClient = new HttpClient())
            {
                //Dodanie przed using naglowka autoryzacji z tokenem
                httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _JWToken.TokenString);
                using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    t = JsonConvert.DeserializeObject<Trener>(apiResponse);
                }
            }
            return View(t);
        }

        // GET: TrenerzyController/Create
        public async Task<ActionResult> Create()
        {
            Trener t = new Trener();
            return View(t);
        }

        // POST: TrenerzyController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Create(IFormCollection collection)
        {
            _restpath = $"{OnGet().Content}{_controllername}";

            Trener t = new Trener();
            t.Imie = collection["Imie"];
            t.Nazwisko = collection["Nazwisko"];
            t.Team = collection["Team"];

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonStr = System.Text.Json.JsonSerializer.Serialize(t);
                    var content = new StringContent(jsonStr, Encoding.UTF8, "application/json");

                    //Dodanie przed using naglowka autoryzacji z tokenem
                    httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _JWToken.TokenString);
                    using (var response = await httpClient.PostAsync($"{_restpath}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        t = JsonConvert.DeserializeObject<Trener>(apiResponse);
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TrenerzyController/Edit/{id}
        //Brak deklaracji [HttpPost] lub innej metody - Akcja przekazana do metody Details w biezacym kontrolerze
        public async Task<ActionResult> Edit(int id)
        {
            _restpath = $"{OnGet().Content}{_controllername}";

            Trener t = new Trener();

            using (var httpClient = new HttpClient())
            {
                //Dodanie przed using naglowka autoryzacji z tokenem
                httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _JWToken.TokenString);
                using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                {                    
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    t = JsonConvert.DeserializeObject<Trener>(apiResponse);
                }
            }

            return View(t);
        }

        // POST: TrenerzyController/Edit/5
        // Deklaracja [HttpPost] Akcja przekazana do metody Details w REST (tu Post)
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Edit(int id, IFormCollection collection)
        {
            _restpath = $"{OnGet().Content}{_controllername}";

            //Tu przesłanie w ciele Body
            Trener t = new Trener();
            t.Id = Convert.ToInt32(collection["Id"]);
            t.Imie = collection["Imie"];
            t.Nazwisko = collection["Nazwisko"];
            t.Team = collection["Team"];

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonStr = System.Text.Json.JsonSerializer.Serialize(t);
                    var content = new StringContent(jsonStr, Encoding.UTF8, "application/json");

                    //Dodanie przed using naglowka autoryzacji z tokenem
                    httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _JWToken.TokenString);
                    using (var response = await httpClient.PutAsync($"{_restpath}/{id}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        t = JsonConvert.DeserializeObject<Trener>(apiResponse);
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TrenerzyController/Delete/{id}
        // Pobranie trenera i zatweirdzenie jego usunięcia
        public async Task<ActionResult> Delete(int id)
        {
            _restpath = $"{OnGet().Content}{_controllername}";

            Trener t = new Trener();
            using (var httpClient = new HttpClient())
            {
                //Dodanie przed using naglowka autoryzacji z tokenem
                httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _JWToken.TokenString);
                using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    t = JsonConvert.DeserializeObject<Trener>(apiResponse);
                }
            }
            return View(t);
        }

        // POST: TrenerzyController/Delete/{id}
        //Wysłanie zadania usuniecia trenera do REST Zawodnicy.API
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Delete(int id, IFormCollection collection)
        {
            _restpath = $"{OnGet().Content}{_controllername}";

            //collection tu nie wykorzystujemy
            //Potem tak naprawde juz tylko Id bedzie potrzebne ale tu wywolamy calosc trenara

            try
            {
                using (var httpClient = new HttpClient())
                {
                    //Dodanie przed using naglowka autoryzacji z tokenem
                    httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _JWToken.TokenString);
                    using (var response = await httpClient.DeleteAsync($"{_restpath}/{id}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        //z = JsonConvert.DeserializeObject<Zawodnik>(apiResponse);
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Zawodnicy/ZawodnicyWebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Zawodnicy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/sysuniamini.png" height="50" />
                </a>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Zawodnicy</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Start</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Info</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Zawodnicy" asp-action="Index">Lista Zawodników</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trenerzy" asp-action="Index">Lista Trenerów</a>
                        </li>

                        @* Tajne dla roli "wazny" lub "zarzadca" *@
                        @{
                            if (User.IsInRole("zarzadca") || User.IsInRole("wazny"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Tajne" asp-action="Index">*Materiały</a>
                                </li>
                            }
                            else  //tylko wyswietl nieaktywną opcję
                            {
                                <li class="nav-link text-dark">
                                    <span style="color:darkgray">*Materiały</span>
                                </li>
                            }
                        }


                        @* Panel administracyjny TYLKO dla roli "zarzadca" *@
                        @{
                            if (User.IsInRole("zarzadca"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="PanelAdministracyjny" asp-action="Index">**Panel administracyjny</a>
                                </li>
                            }
                            else  //tylko wyswietl nieaktywną opcję
                            {
                                <li class="nav-link text-dark">
                                    <span style="color:darkgray">**Panel administracyjny</span>
                                </li>
                            }
                        }




                    <li class="nav-item">
                        @*<a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Zarejestruj się</a>*@
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="RegisterWithConfirm">Zarejestruj się</a>
                    </li>

                        @* Wylogowanie, Zalogowanie, Zalogowany user *@
                        @if (SignInManager.IsSignedIn(User))
                        {

                            <li class="nav-link text-dark">
                                @*<a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Witaj @User.Identity.Name</a>*@
                                Witaj @User.Identity.Name
                            </li>
                            <li class="nav-link text-dark">
                                <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm" method="post" class="navbar-right">
                                    <a href="javascript:document.getElementById('logoutForm').submit()">Wyloguj</a>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Zaloguj się</a>
                            </li>
                        }




                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 by Mirek Juszczak - <a asp-area="" asp-controller="Home" asp-action="Privacy">Info</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>